#!/bin/bash
# chkconfig: 2345 20 80
# knocker 
# description: daemon of authentication server

prog=knocker
binary=/usr/bin/$prog
pidfile=/var/run/$prog.pid

case "$1" in
start)
  if [ -f $pidfile ] 
  then
    echo "$prog has already been started"
  else
    echo "Starting $prog"
    $binary
  fi
  ;;
stop)
  if [ -f $pidfile ]
  then
    echo "Stopping $prog"
    kill -s SIGTERM `cat $pidfile`
    rm -f $pidfile
  else
    echo "$prog is not working now"
  fi
  ;;
reload)
  $0 stop
  $0 start
  ;;
status)
  if [ -f $pidfile ]
  then
    echo "$prog is running";
  else
    echo "$prog is not running";
  fi
  ;;
*)
  echo "Usage: $0 {start|stop|reload|status}"
esac

exit 0
